spring:
  application:
    name: gerenciadortarefas

  datasource:
    url: jdbc:postgresql://localhost:5432/seu_database
    username: seu_username
    password: sua_senha
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      format-sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



